# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 08:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('desactivo', 'desactivo')], default='activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('nro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('proceso', 'proceso'), ('terminado', 'terminado'), ('otro', 'fallo')], default='proceso', max_length=20)),
                ('cod_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Almacen')),
                ('cod_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingreso_proveedor', to='inventario.Proveedor')),
                ('cod_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nota_Detalle',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('total', models.FloatField()),
                ('cod_ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_detalle_ingreso', to='comprobante.Ingreso')),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('nro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('tipo_cambio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo', models.CharField(choices=[('salida', 'Salida'), ('proforma', 'Proforma')], max_length=10)),
                ('estado', models.CharField(choices=[('proceso', 'proceso'), ('terminado', 'terminado'), ('otro', 'fallo')], default='proceso', max_length=20)),
                ('cod_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida_almacenes', to='inventario.Almacen')),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida_cliente', to='comprobante.Cliente')),
                ('cod_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transpaso',
            fields=[
                ('nro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('proceso', 'proceso'), ('terminado', 'terminado'), ('otro', 'fallo')], default='proceso', max_length=20)),
                ('cod_almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacen_destino', to='inventario.Almacen')),
                ('cod_almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacen_origen', to='inventario.Almacen')),
                ('cod_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('tipo', models.IntegerField()),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('desactivo', 'desactivo')], default='activo', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='nota_detalle',
            name='cod_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_detalle_salida', to='comprobante.Salida'),
        ),
        migrations.AddField(
            model_name='nota_detalle',
            name='cod_transpaso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_detalle_transpaso', to='comprobante.Transpaso'),
        ),
    ]
