# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='cod_almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Almacen', verbose_name='Almacen'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='cod_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingreso_proveedor', to='inventario.Proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='cod_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='nota_detalle',
            name='cod_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='nota_detalle',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='salida',
            name='cod_almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida_almacenes', to='inventario.Almacen', verbose_name='Almacen'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='cod_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida_cliente', to='comprobante.Cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='cod_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entrega'),
        ),
        migrations.AlterField(
            model_name='transpaso',
            name='cod_almacen_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacen_destino', to='inventario.Almacen', verbose_name='Almacen Destino'),
        ),
        migrations.AlterField(
            model_name='transpaso',
            name='cod_almacen_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacen_origen', to='inventario.Almacen', verbose_name='Almacen Origen'),
        ),
        migrations.AlterField(
            model_name='transpaso',
            name='cod_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
