# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20170519_0621'),
        ('comprobante', '0004_detalle_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Traspaso',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('total', models.FloatField(default=0)),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto', verbose_name='Producto')),
            ],
        ),
        migrations.RenameModel(
            old_name='Transpaso',
            new_name='Traspaso',
        ),
        migrations.RemoveField(
            model_name='nota_detalle',
            name='cod_ingreso',
        ),
        migrations.RemoveField(
            model_name='nota_detalle',
            name='cod_producto',
        ),
        migrations.RemoveField(
            model_name='nota_detalle',
            name='cod_salida',
        ),
        migrations.RemoveField(
            model_name='nota_detalle',
            name='cod_transpaso',
        ),
        migrations.DeleteModel(
            name='Nota_Detalle',
        ),
        migrations.AddField(
            model_name='detalle_traspaso',
            name='cod_traspaso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_traspaso', to='comprobante.Traspaso'),
        ),
    ]
