# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 08:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante', '0005_auto_20170603_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Entrega'),
        ),
    ]
