# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20170514_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cod_almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenes', to='inventario.Almacen', verbose_name='almacen'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cod_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.Producto', verbose_name='Producto'),
        ),
    ]
