# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20170515_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['cantidad']},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set([('cod_almacen', 'cantidad')]),
        ),
    ]
