# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20170515_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set([]),
        ),
    ]
